### PR TITLE
Add PyLabLib to alternatives

### PR DESCRIPTION
**Pull request by kadykov**

### CODE REVIEW

**Review by untzag — APPROVED** [review]
Thanks for the contribution @kadykov

**Comment by untzag** [comment]
Thanks for your big contributions to the alternatives page @kadykov! As you can probably tell, I originally wanted to have a great alternatives page but ended up not giving it the attention it deserves :confounded:.

Since you seem to be thinking about alternatives I want to link you to the following (which you may have already seen)

https://github.com/LabPy/labpy-discussion/issues/23

https://github.com/python-data-acquisition/meta/blob/master/existing_packages.md

https://github.com/pyinstruments/pyinstruments

I personally also have a blog post where I try to simply LIST the projects... 

https://blog.blaise.zone/hardware-control/

Thanks again for choosing to make contributions to yaq-fyi :smile:

**Comment by kadykov** [comment]
Thank you for the useful links, the list on your blog is really impressive!
And thank you for the yaq project!

p.s.
Do you know that yaqd-core-python.yaq.fyi is down?

**Comment by untzag** [comment]
Gosh, I did know that yaqd-core-python was down! We used to serve API docs at that subdomain, but the tool we used to build those docs broke upstream and we never fixed it! I don't even remember the name of the tool we used anymore..

Thanks for your attention to detail @kadykov, I'll open a PR to remove that link right away.

**Pull request merged**
